# Generated by Django 3.1.7 on 2023-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
