# Generated by Django 3.1.7 on 2023-08-11 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_room_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players_ready',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
