# Generated by Django 3.1.7 on 2023-08-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_room_players_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='state',
            new_name='status',
        ),
    ]
