# Generated by Django 3.1.7 on 2023-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_room_ready_smart_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_players_ready_from_smart_contract',
            field=models.BooleanField(default=False),
        ),
    ]
