export const LOADING_PAGE = "LOADING_PAGE";
export const STOP_LOADING_PAGE = "STOP_LOADING_PAGE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SET_USERS = "SET_USERS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

// PERFIL
export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_STATUS = "SET_PROFILE_STATUS";
// export const GET_PROFILE = "GET_PROFILE";
// export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const CLEAR_STATUS = "CLEAR_STATUS";

export const SET_MODULES = "SET_MODULES";
export const GET_MODULES_ERROR = "GET_MODULES_ERROR";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const APPEND_NOTIFICATION = "APPEND_NOTIFICATION";

export const SET_ALERT = "SET_ALERT";

// INITIAL INFO
export const SET_MODULES_ACTIONS_PERMISSIONS =
    "SET_MODULES_ACTIONS_PERMISSIONS";
